#!/usr/bin/env python
# Anthor: Huang jianqiang
# From: Shenzhen
# Date: 2017-01-09
# Description: the executor


import sys

import FoldAnalyze

if __name__ == '__main__':

    if len(sys.argv) == 1:
        root = '.'
        FoldAnalyze.FoldAnalyze(root)
    else:
        root = sys.argv[1]
        FoldAnalyze.FoldAnalyze(root)

