#!/usr/bin/env python
# Anthor: Huang jianqiang
# From: Shenzhen
# Date: 2017-01-09
# Description: the executor


import sys

from FoldAnalyze import FoldSizeAnalyze, FoldStructureAnalyze

if __name__ == '__main__':

    argvs = sys.argv
    if len(argvs) == 1:
        print 'Need some parameters like -s<size> -l<list>'
    else:
        if '-s' in argvs:
            argvs.remove('-s')
            if len(argvs) == 2: # assume remain path
                root = argvs[1]
            elif len(argvs) == 1:
                root = '.'
            FoldSizeAnalyze(root)
        elif '-l' in argvs:
            argvs.remove('-l')
            isDetail = True
            if '-d' in argvs:
                isDetail = False
                argvs.remove('-d')
            if len(argvs) == 1: # assume remain path
                root = '.'
            else:
                root = sys.argv[1]
            print argvs
            FoldStructureAnalyze().showDirTree(root, isDetail)

