#!/usr/bin/env python
# Anthor: Huang jianqiang
# From: Shenzhen
# Date: 2017-01-11
# Description: the executor to show the structure of fold


import sys

from FoldAnalyze import FoldStructureAnalyze

if __name__ == '__main__':

    if len(sys.argv) == 1:
        root = '.'
    else:
        root = sys.argv[1]

    FoldStructureAnalyze().showDirTree(root)


